services:
  - type: web
    name: philosopher-chat
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false # This means you'll need to set it manually in the dashboard
